In [ ]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

df = pd.read_csv('twitter_dataset.csv')
df['Timestamp'] = pd.to_datetime(df['Timestamp']) #converting string to datetime object
df.head(3)

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,Party least receive say or single. Prevent pre...,2,25,2023-01-30 11:00:51
1,2,richardhester,Hotel still Congress may member staff. Media d...,35,29,2023-01-02 22:45:58
2,3,williamsjoseph,Nice be her debate industry that year. Film wh...,51,25,2023-01-18 11:25:19

In [17]:
analyzer = SentimentIntensityAnalyzer() #VADER ONNN!!!!!


scores = df['Text'].apply(analyzer.polarity_scores) # assigns different scores to the text in the data, basically does that to each row of the text column  
sentiment_df = pd.DataFrame(scores.tolist()) # convert list of dicts to df 
df[['pos', 'neg', 'neu', 'compound_score']] = sentiment_df[['pos', 'neg', 'neu', 'compound']].values
df[['Text', 'pos', 'neg', 'neu', 'compound_score']].head()

,Text,pos,neg,neu,compound_score
0,Party least receive say or single. Prevent pre...,0.325,0.00,0.675,0.8885
1,Hotel still Congress may member staff. Media d...,0.071,0.00,0.929,0.2960
2,Nice be her debate industry that year. Film wh...,0.235,0.00,0.765,0.8481
3,Laugh explain situation career occur serious. ...,0.165,0.04,0.795,0.6249
4,Involve sense former often approach government...,0.153,0.00,0.847,0.6705

In [ ]:
def get_label(compound): # function to give lavel to the score, less than -0.05 is negative, more than 0.05 is positive, in between is neutral
    if compound >= 0.05:
        return 'positive'
    elif compound <= -0.05:
        return 'negative'
    else:
        return 'neutral'

df['sentiment_label'] = df['compound_score'].apply(get_label) #now gets the label for each row's compound score
print(df['sentiment_label'].value_counts())

sentiment_label
positive    7934
negative    1682
neutral      384
Name: count, dtype: int64

In [ ]:
df.to_csv('tweets_with_sentiment.csv', index=False) #makes new csv with new columns for the sentiment scores and labels
print('Done! Columns:', list(df.columns))